### ISSUE TITLE
Output Log errors

### ISSUE THREAD

**Issue by ikonnow** [GodotVR/godot-xr-tools#561] opened 2023-11-04 11:31 UTC
Hello, this is kind of an FYI.
I encountered quite some errors after installing the "Godot XR Tools for Godot 4" from AssetLib (v.s 4.2.beta4). Then after reopening the project the Output is cleared. Maybe there is a way to avoid it?
Would be nice or a better launching experience I guess :).

```
Godot Engine v4.2.beta4.official (c) 2007-present Juan Linietsky, Ariel Manzur & Godot Contributors.
--- Debug adapter server started ---
--- GDScript language server started on port 6005 ---
  scene/resources/importer_mesh.cpp:518 - Ignoring face with non-finite normal in LOD generation.
  res://addons/godot-xr-tools/player/player_body.gd:435 - Parse Error: Identifier "XRToolsUserSettings" not declared in the current scope.
  modules/gdscript/gdscript.cpp:2703 - Failed to load script "res://addons/godot-xr-tools/player/player_body.gd" with error "Parse error". (User)
  res://addons/godot-xr-tools/player/player_body.gd:435 - Parse Error: Identifier "XRToolsUserSettings" not declared in the current scope.
  res://addons/godot-xr-tools/functions/movement_provider.gd:-1 - Compile Error: 
  res://addons/godot-xr-tools/player/player_body.gd:435 - Parse Error: Identifier "XRToolsUserSettings" not declared in the current scope.
  res://addons/godot-xr-tools/examples/fall_damage.gd:-1 - Compile Error: 
  modules/gdscript/gdscript.cpp:2703 - Failed to load script "res://addons/godot-xr-tools/examples/fall_damage.gd" with error "Compilation failed". (User)
  res://addons/godot-xr-tools/player/player_body.gd:435 - Parse Error: Identifier "XRToolsUserSettings" not declared in the current scope.
  res://addons/godot-xr-tools/functions/function_teleport.gd:-1 - Compile Error: 
  modules/gdscript/gdscript.cpp:2703 - Failed to load script "res://addons/godot-xr-tools/functions/function_teleport.gd" with error "Compilation failed". (User)
  res://addons/godot-xr-tools/player/player_body.gd:435 - Parse Error: Identifier "XRToolsUserSettings" not declared in the current scope.
  res://addons/godot-xr-tools/functions/movement_climb.gd:-1 - Compile Error: 
  modules/gdscript/gdscript.cpp:2703 - Failed to load script "res://addons/godot-xr-tools/functions/movement_climb.gd" with error "Compilation failed". (User)
  res://addons/godot-xr-tools/player/player_body.gd:435 - Parse Error: Identifier "XRToolsUserSettings" not declared in the current scope.
  res://addons/godot-xr-tools/functions/movement_crouch.gd:-1 - Compile Error: 
  modules/gdscript/gdscript.cpp:2703 - Failed to load script "res://addons/godot-xr-tools/functions/movement_crouch.gd" with error "Compilation failed". (User)
  res://addons/godot-xr-tools/functions/movement_direct.gd:44 - Parse Error: Identifier "XRToolsUserSettings" not declared in the current scope.
  modules/gdscript/gdscript.cpp:2703 - Failed to load script "res://addons/godot-xr-tools/functions/movement_direct.gd" with error "Parse error". (User)
  res://addons/godot-xr-tools/player/player_body.gd:435 - Parse Error: Identifier "XRToolsUserSettings" not declared in the current scope.
  res://addons/godot-xr-tools/functions/movement_flight.gd:-1 - Compile Error: 
  modules/gdscript/gdscript.cpp:2703 - Failed to load script "res://addons/godot-xr-tools/functions/movement_flight.gd" with error "Compilation failed". (User)
  res://addons/godot-xr-tools/player/player_body.gd:435 - Parse Error: Identifier "XRToolsUserSettings" not declared in the current scope.
  res://addons/godot-xr-tools/functions/movement_footstep.gd:-1 - Compile Error: 
  modules/gdscript/gdscript.cpp:2703 - Failed to load script "res://addons/godot-xr-tools/functions/movement_footstep.gd" with error "Compilation failed". (User)
  res://addons/godot-xr-tools/player/player_body.gd:435 - Parse Error: Identifier "XRToolsUserSettings" not declared in the current scope.
  res://addons/godot-xr-tools/functions/movement_glide.gd:-1 - Compile Error: 
  modules/gdscript/gdscript.cpp:2703 - Failed to load script "res://addons/godot-xr-tools/functions/movement_glide.gd" with error "Compilation failed". (User)
  res://addons/godot-xr-tools/player/player_body.gd:435 - Parse Error: Identifier "XRToolsUserSettings" not declared in the current scope.
  res://addons/godot-xr-tools/functions/movement_grapple.gd:-1 - Compile Error: 
  modules/gdscript/gdscript.cpp:2703 - Failed to load script "res://addons/godot-xr-tools/functions/movement_grapple.gd" with error "Compilation failed". (User)
  res://addons/godot-xr-tools/player/player_body.gd:435 - Parse Error: Identifier "XRToolsUserSettings" not declared in the current scope.
  res://addons/godot-xr-tools/functions/movement_jump.gd:-1 - Compile Error: 
  modules/gdscript/gdscript.cpp:2703 - Failed to load script "res://addons/godot-xr-tools/functions/movement_jump.gd" with error "Compilation failed". (User)
  res://addons/godot-xr-tools/player/player_body.gd:435 - Parse Error: Identifier "XRToolsUserSettings" not declared in the current scope.
  res://addons/godot-xr-tools/functions/movement_physical_jump.gd:-1 - Compile Error: 
  modules/gdscript/gdscript.cpp:2703 - Failed to load script "res://addons/godot-xr-tools/functions/movement_physical_jump.gd" with error "Compilation failed". (User)
  res://addons/godot-xr-tools/functions/movement_direct.gd:44 - Parse Error: Identifier "XRToolsUserSettings" not declared in the current scope.
  res://addons/godot-xr-tools/player/player_body.gd:435 - Parse Error: Identifier "XRToolsUserSettings" not declared in the current scope.
  res://addons/godot-xr-tools/functions/movement_sprint.gd:-1 - Compile Error: 
  modules/gdscript/gdscript.cpp:2703 - Failed to load script "res://addons/godot-xr-tools/functions/movement_sprint.gd" with error "Compilation failed". (User)
  res://addons/godot-xr-tools/functions/movement_turn.gd:111 - Parse Error: Identifier "XRToolsUserSettings" not declared in the current scope.
  modules/gdscript/gdscript.cpp:2703 - Failed to load script "res://addons/godot-xr-tools/functions/movement_turn.gd" with error "Parse error". (User)
  res://addons/godot-xr-tools/player/player_body.gd:435 - Parse Error: Identifier "XRToolsUserSettings" not declared in the current scope.
  res://addons/godot-xr-tools/functions/movement_wall_walk.gd:-1 - Compile Error: 
  modules/gdscript/gdscript.cpp:2703 - Failed to load script "res://addons/godot-xr-tools/functions/movement_wall_walk.gd" with error "Compilation failed". (User)
  res://addons/godot-xr-tools/player/player_body.gd:435 - Parse Error: Identifier "XRToolsUserSettings" not declared in the current scope.
  res://addons/godot-xr-tools/functions/movement_wind.gd:-1 - Compile Error: 
  modules/gdscript/gdscript.cpp:2703 - Failed to load script "res://addons/godot-xr-tools/functions/movement_wind.gd" with error "Compilation failed". (User)
  res://addons/godot-xr-tools/player/player_body.gd:435 - Parse Error: Identifier "XRToolsUserSettings" not declared in the current scope.
  res://addons/godot-xr-tools/objects/teleport_area.gd:-1 - Compile Error: 
  modules/gdscript/gdscript.cpp:2703 - Failed to load script "res://addons/godot-xr-tools/objects/teleport_area.gd" with error "Compilation failed". (User)
  res://addons/godot-xr-tools/user_settings/user_settings_ui.gd:13 - Parse Error: Identifier "XRToolsUserSettings" not declared in the current scope.
  res://addons/godot-xr-tools/user_settings/user_settings_ui.gd:14 - Parse Error: Identifier "XRToolsUserSettings" not declared in the current scope.
  res://addons/godot-xr-tools/user_settings/user_settings_ui.gd:15 - Parse Error: Identifier "XRToolsUserSettings" not declared in the current scope.
  res://addons/godot-xr-tools/user_settings/user_settings_ui.gd:18 - Parse Error: Identifier "XRToolsUserSettings" not declared in the current scope.
  res://addons/godot-xr-tools/user_settings/user_settings_ui.gd:21 - Parse Error: Identifier "XRToolsUserSettings" not declared in the current scope.
  res://addons/godot-xr-tools/user_settings/user_settings_ui.gd:29 - Parse Error: Identifier "XRToolsUserSettings" not declared in the current scope.
  res://addons/godot-xr-tools/user_settings/user_settings_ui.gd:36 - Parse Error: Identifier "XRToolsUserSettings" not declared in the current scope.
  res://addons/godot-xr-tools/user_settings/user_settings_ui.gd:38 - Parse Error: Identifier "XRToolsUserSettings" not declared in the current scope.
  res://addons/godot-xr-tools/user_settings/user_settings_ui.gd:42 - Parse Error: Identifier "XRToolsUserSettings" not declared in the current scope.
  res://addons/godot-xr-tools/user_settings/user_settings_ui.gd:43 - Parse Error: Identifier "XRToolsUserSettings" not declared in the current scope.
  res://addons/godot-xr-tools/user_settings/user_settings_ui.gd:45 - Parse Error: Identifier "XRToolsUserSettings" not declared in the current scope.
  res://addons/godot-xr-tools/user_settings/user_settings_ui.gd:50 - Parse Error: Identifier "XRToolsUserSettings" not declared in the current scope.
  res://addons/godot-xr-tools/user_settings/user_settings_ui.gd:55 - Parse Error: Identifier "XRToolsUserSettings" not declared in the current scope.
  res://addons/godot-xr-tools/user_settings/user_settings_ui.gd:56 - Parse Error: Identifier "XRToolsUserSettings" not declared in the current scope.
  res://addons/godot-xr-tools/user_settings/user_settings_ui.gd:60 - Parse Error: Identifier "XRToolsUserSettings" not declared in the current scope.
  res://addons/godot-xr-tools/user_settings/user_settings_ui.gd:64 - Parse Error: Identifier "XRToolsUserSettings" not declared in the current scope.
  res://addons/godot-xr-tools/user_settings/user_settings_ui.gd:67 - Parse Error: Identifier "XRToolsUserSettings" not declared in the current scope.
  modules/gdscript/gdscript.cpp:2703 - Failed to load script "res://addons/godot-xr-tools/user_settings/user_settings_ui.gd" with error "Parse error". (User)
  core/io/resource_format_binary.cpp:1054 - res://addons/godot-xr-tools/hands/materials/african_hands.material: In external resource #0, invalid UID: uid://ijfutijrsylw - using text path instead: res://addons/godot-xr-tools/hands/textures/african_baseColor.png
  core/io/resource_format_binary.cpp:1054 - res://addons/godot-xr-tools/hands/materials/african_hands.material: In external resource #1, invalid UID: uid://c64s2fj3d1m8s - using text path instead: res://addons/godot-xr-tools/hands/textures/hands_occlusionRoughnessMetallic.png
res://addons/godot-xr-tools/hands/textures/african_baseColor.png: Texture detected as used in 3D. Enabling mipmap generation and setting the texture compression mode to VRAM Compressed (S3TC/ETC/BPTC).
  core/io/resource_format_binary.cpp:1054 - res://addons/godot-xr-tools/hands/materials/african_hands_realistic.material: In external resource #0, invalid UID: uid://cnmcg22m0soxy - using text path instead: res://addons/godot-xr-tools/hands/textures/african_realistic_baseColor.png
  core/io/resource_format_binary.cpp:1054 - res://addons/godot-xr-tools/hands/materials/african_hands_realistic.material: In external resource #1, invalid UID: uid://c64s2fj3d1m8s - using text path instead: res://addons/godot-xr-tools/hands/textures/hands_occlusionRoughnessMetallic.png
  core/io/resource_format_binary.cpp:1054 - res://addons/godot-xr-tools/hands/materials/african_hands_realistic.material: In external resource #2, invalid UID: uid://dohtj55yf3eti - using text path instead: res://addons/godot-xr-tools/hands/textures/hands_normal.png
res://addons/godot-xr-tools/hands/textures/african_realistic_baseColor.png: Texture detected as used in 3D. Enabling mipmap generation and setting the texture compression mode to VRAM Compressed (S3TC/ETC/BPTC).
res://addons/godot-xr-tools/hands/textures/hands_normal.png: Texture detected as used as a normal map in 3D. Enabling red-green texture compression to reduce memory usage (blue channel is discarded).
res://addons/godot-xr-tools/hands/textures/hands_normal.png: Texture detected as used as a roughness map in 3D. Enabling roughness limiter based on the detected associated normal map at res://addons/godot-xr-tools/hands/textures/hands_normal.png.
res://addons/godot-xr-tools/hands/textures/hands_normal.png: Texture detected as used in 3D. Enabling mipmap generation and setting the texture compression mode to VRAM Compressed (S3TC/ETC/BPTC).
  core/io/resource_format_binary.cpp:1054 - res://addons/godot-xr-tools/hands/materials/caucasian_hand.material: In external resource #0, invalid UID: uid://dh7rys3who35c - using text path instead: res://addons/godot-xr-tools/hands/textures/caucasian_baseColor.png
  core/io/resource_format_binary.cpp:1054 - res://addons/godot-xr-tools/hands/materials/caucasian_hand.material: In external resource #1, invalid UID: uid://c64s2fj3d1m8s - using text path instead: res://addons/godot-xr-tools/hands/textures/hands_occlusionRoughnessMetallic.png
  core/io/resource_format_binary.cpp:1054 - res://addons/godot-xr-tools/hands/materials/caucasian_hands_realistic.material: In external resource #0, invalid UID: uid://buo1o13fo7okd - using text path instead: res://addons/godot-xr-tools/hands/textures/caucasian_realistic_baseColor.png
  core/io/resource_format_binary.cpp:1054 - res://addons/godot-xr-tools/hands/materials/caucasian_hands_realistic.material: In external resource #1, invalid UID: uid://c64s2fj3d1m8s - using text path instead: res://addons/godot-xr-tools/hands/textures/hands_occlusionRoughnessMetallic.png
  core/io/resource_format_binary.cpp:1054 - res://addons/godot-xr-tools/hands/materials/caucasian_hands_realistic.material: In external resource #2, invalid UID: uid://dohtj55yf3eti - using text path instead: res://addons/godot-xr-tools/hands/textures/hands_normal.png
res://addons/godot-xr-tools/hands/textures/caucasian_realistic_baseColor.png: Texture detected as used in 3D. Enabling mipmap generation and setting the texture compression mode to VRAM Compressed (S3TC/ETC/BPTC).
  core/io/resource_format_binary.cpp:1054 - res://addons/godot-xr-tools/hands/materials/cleaning_glove.material: In external resource #0, invalid UID: uid://c5cnjs0vgmwpb - using text path instead: res://addons/godot-xr-tools/hands/textures/cleaning_glove_baseColor.png
  core/io/resource_format_binary.cpp:1054 - res://addons/godot-xr-tools/hands/materials/cleaning_glove.material: In external resource #1, invalid UID: uid://bpr3hcb5m0pkc - using text path instead: res://addons/godot-xr-tools/hands/textures/glove_occlusionRoughnessMetallic.png
  core/io/resource_format_binary.cpp:1054 - res://addons/godot-xr-tools/hands/materials/cleaning_glove.material: In external resource #2, invalid UID: uid://dnlns2kfjkwhh - using text path instead: res://addons/godot-xr-tools/hands/textures/glove_normal.png
  core/io/resource_format_binary.cpp:1054 - res://addons/godot-xr-tools/hands/materials/glove_african_dark_camo.material: In external resource #0, invalid UID: uid://bf5sf1lr5enkj - using text path instead: res://addons/godot-xr-tools/hands/textures/glove_african_dark_camo.png
  core/io/resource_format_binary.cpp:1054 - res://addons/godot-xr-tools/hands/materials/glove_african_dark_camo.material: In external resource #1, invalid UID: uid://dq1hgb151kqbm - using text path instead: res://addons/godot-xr-tools/hands/textures/glove_fingerless_occlusionRoughnessMetallic.png
  core/io/resource_format_binary.cpp:1054 - res://addons/godot-xr-tools/hands/materials/glove_african_dark_camo.material: In external resource #2, invalid UID: uid://g1q2fw3his2p - using text path instead: res://addons/godot-xr-tools/hands/textures/glove_fingerless_normal.png
res://addons/godot-xr-tools/hands/textures/glove_african_dark_camo.png: Texture detected as used in 3D. Enabling mipmap generation and setting the texture compression mode to VRAM Compressed (S3TC/ETC/BPTC).
  core/io/resource_format_binary.cpp:1054 - res://addons/godot-xr-tools/hands/materials/glove_caucasian_dark_camo.material: In external resource #0, invalid UID: uid://bv8f10trc82to - using text path instead: res://addons/godot-xr-tools/hands/textures/glove_caucasian_dark_camo.png
  core/io/resource_format_binary.cpp:1054 - res://addons/godot-xr-tools/hands/materials/glove_caucasian_dark_camo.material: In external resource #1, invalid UID: uid://dq1hgb151kqbm - using text path instead: res://addons/godot-xr-tools/hands/textures/glove_fingerless_occlusionRoughnessMetallic.png
  core/io/resource_format_binary.cpp:1054 - res://addons/godot-xr-tools/hands/materials/glove_caucasian_dark_camo.material: In external resource #2, invalid UID: uid://g1q2fw3his2p - using text path instead: res://addons/godot-xr-tools/hands/textures/glove_fingerless_normal.png
  core/io/resource_format_binary.cpp:1054 - res://addons/godot-xr-tools/hands/materials/glove_caucasian_green_camo.material: In external resource #0, invalid UID: uid://c46jhbxjlf4t1 - using text path instead: res://addons/godot-xr-tools/hands/textures/glove_caucasian_green_camo.png
  core/io/resource_format_binary.cpp:1054 - res://addons/godot-xr-tools/hands/materials/glove_caucasian_green_camo.material: In external resource #1, invalid UID: uid://dq1hgb151kqbm - using text path instead: res://addons/godot-xr-tools/hands/textures/glove_fingerless_occlusionRoughnessMetallic.png
  core/io/resource_format_binary.cpp:1054 - res://addons/godot-xr-tools/hands/materials/glove_caucasian_green_camo.material: In external resource #2, invalid UID: uid://g1q2fw3his2p - using text path instead: res://addons/godot-xr-tools/hands/textures/glove_fingerless_normal.png
  core/io/resource_format_binary.cpp:1054 - res://addons/godot-xr-tools/hands/materials/labglove.material: In external resource #0, invalid UID: uid://bv21ei62pffeb - using text path instead: res://addons/godot-xr-tools/hands/textures/labglove_baseColor.png
  core/io/resource_format_binary.cpp:1054 - res://addons/godot-xr-tools/hands/materials/labglove.material: In external resource #1, invalid UID: uid://bpr3hcb5m0pkc - using text path instead: res://addons/godot-xr-tools/hands/textures/glove_occlusionRoughnessMetallic.png
  core/io/resource_format_binary.cpp:1054 - res://addons/godot-xr-tools/hands/materials/labglove.material: In external resource #2, invalid UID: uid://dnlns2kfjkwhh - using text path instead: res://addons/godot-xr-tools/hands/textures/glove_normal.png
```

Thank you for your attention and your work on this plugin.

**Comment by BastiaanOlij** [comment] 2023-11-16 23:52
@ikonnow it's annoying as heck that Godot does not enable plugins by default, I've died on that hill a few times already but it's the cause of the biggest issue, the unknown `XRToolsUserSettings` which is an object that gets configured when the plugin is enabled.

Just go to project settings, go to the plugin tab, and enable XR tools.

The UID and conversion warnings we plan to address soon, we've left this open because changes in Godot kept pulling the rug out from underneath us. This should now all have stabilised so part of the next release of XR Tools will be cleaning up all the missing/incorrect UIDs and updating the plugin.

**Comment by ikonnow** [comment] 2023-11-17 04:04
Thank you very much for your answer and for taking note, I can absolutely understand that. Of course, this is a detail that at the end of the day falls into the user experience category. However, I am convinced that it initially puts many people off. Which is not a particularly good start, especially for users who are familiar with engines like Unity and Unreal.

Thanks for your great work, we've been using Godot in my studio for almost a year now and I'm convinced that after overcoming a few small hurdles you can achieve wonderful results in XR!

**Comment by Malcolmnixon** [comment] 2023-11-25 19:16
Godot 4.2 is doing much better at script resolving on first start, but I think it still has one or two issues like this. The team has been working hard at improving this part of the engine. The progress was actually mentioned in a GodotCon 2023 talk - https://www.youtube.com/watch?v=WNR4Tne5DRE

**Comment by ikonnow** [comment] 2023-11-25 20:39
> Godot 4.2 is doing much better at script resolving on first start, but I think it still has one or two issues like this. The team has been working hard at improving this part of the engine. The progress was actually mentioned in a GodotCon 2023 talk - https://www.youtube.com/watch?v=WNR4Tne5DRE
> 

Thanks for the Link. I didn't have the chance to go over the the GodotCon content yet but I will!. I was working with every single updated 4.2 beta and I will test the second RC in the context of these messages again. Since I'm about to release an application with my team and most of the time Godot felt just a little rough but stable, I'm not sure if this bug is worth existing longer. I guess that's the context of your hint as well. 

Also I'd like to mention the XR template version of "foobar404" was helping a lot. And if love to see the current official version! Thanks for the great work, I'm looking forward to the official release

**Closed** 2023-11-25 20:39 UTC
