### ISSUE TITLE
SnapZone does not work if you remove it from the player's object

### ISSUE THREAD

**Issue by anunknowperson** [GodotVR/godot-xr-tools#446] opened 2023-04-10 14:39 UTC
The ability to use snap_zone.gd outside the player would be useful in a variety of scenarios.

Unfortunately, this does not work now, the area on snap_zone does not register body_enter events, because physical objects move directly through changing their position. When the player releases the object, the area on snap_zone starts registering events.

I don't understand why it works when the area is in the player's object.

How to reproduce: 
Go to pickables demo and detach snap_zone from player object.

**Comment by Malcolmnixon** [comment] 2023-04-10 17:46
I'm not sure exactly what the problem is. The pickables demo scene has numerous snap zones - some attached to the player, and some not:
 - 5x belt snap-zones attached to the player
 - 3x on the teacup stand
 - 1x on the plate
 - 4x on each of the two snap-trays

Please note it's better to use the snap_zone.tscn rather than snap_zone.gd as the scene contains default configuration options and signal wiring necessary for snap-zones to work correctly. We could make the snap_zone.gd somewhat easier to use by wiring the body_entered -> _on_snap_zone_body_entered and body_exited -> _on_snap_zone_body_exited in code rather than in the scene.

**Comment by BastiaanOlij** [comment] 2023-08-29 03:27
Closing this as no further detail provided, as far as we are aware snapzone functionality is working fine.
Do note that you need to use `snapzone.tscn` and extend that scene or use it as is in your scenes.

If there are any further issues please feel free to re-open this or create a new issue with further details.

**Closed by BastiaanOlij** 2023-08-29 03:27 UTC
