### ISSUE TITLE
godot xr tools demo crashes on load 

### ISSUE THREAD

**Issue by hammerandtongs** [GodotVR/godot-xr-tools#417] opened 2023-03-07 03:36 UTC
https://github.com/godotengine/godot/issues/71929#issuecomment-1457414778

But when using xr tools in a fresh project no such crash.

**Comment by BastiaanOlij** [comment] 2023-08-29 03:21
If the issue is Vulkan not starting properly, this is not an issue with Godot XR Tools but Godot itself and already being tracked in the issue referenced in the OP.

Closing this.

**Closed by BastiaanOlij** 2023-08-29 03:21 UTC
