### ISSUE TITLE
Errors with using Viewport2Din3D

### ISSUE THREAD

**Issue by croxis** [GodotVR/godot-xr-tools#49] opened 2021-07-13 20:52 UTC
Pardon what will probably be a rookie mistake! I'm using one Viewport_2D_in_3D. The menu scene is correctly displayed in the godot editor
![image](https://user-images.githubusercontent.com/121591/125522844-b9a711ab-e801-4325-b5b8-49c5cf39c070.png)

However when the scene launches the following errors show up, the Viewport node is white and I can't seem to click on anything.

```
E 0:00:18.356   get_path: Cannot get path of node as it is not in a scene tree.
  <C++ Error>   Condition "!is_inside_tree()" is true. Returned: NodePath()
  <C++ Source>  scene/main/node.cpp:1642 @ get_path()
  <Stack Trace> entry.gd:17 @ _ready()

E 0:00:18.364   get_node: (Node not found: "" (relative to "").)
  <C++ Error>   Condition "!node" is true. Returned: __null
  <C++ Source>  scene/main/node.cpp:1371 @ get_node()
  <Stack Trace> entry.gd:17 @ _ready()

E 0:00:18.371   setup_local_to_scene: ViewportTexture: Path to node is invalid.
  <C++ Error>   Condition "!vpn" is true.
  <C++ Source>  scene/main/viewport.cpp:69 @ setup_local_to_scene()
  <Stack Trace> entry.gd:17 @ _ready()
```

Here is the code throwing the error, although I suspect the actual problem is deeper in the nest

```
extends Node


func _ready() -> void:
    name = 'entry'
    # By default open the client main menu
    var spath: String = "res://client/main_client.tscn"
    if ("--server" in OS.get_cmdline_args() || OS.has_feature("dedicated_server")):
        # Requesting to open in server mode, so change the string to it
        spath = "res://server/main_server.tscn"
        # Cache that we are indeed in server mode
        loader.is_dedicated_server = true
        print("Set to server mode")
    
    # And transition into the appropriate scene
    # warning-ignore:return_value_discarded
    get_tree().change_scene(spath)   # Here is line 17
```

**Comment by BastiaanOlij** [comment] 2021-07-19 02:04
The errors relate to the nodepath defaulting to empty, I think there is one call to _process where the properties haven't been assigned causing this, I'll have to look into that further but it should be assigning your menu scene after that.

I'm not sure why the viewport doesn't render afterwards especially when its working in the editor. What VR plugin are you using, OpenVR? I'll see if I can reproduce it.

**Comment by croxis** [comment] 2021-07-20 14:08
I am using openvr. Do you recommend switching to openxr?

**Comment by BastiaanOlij** [comment] 2021-07-24 08:48
OpenVR should be working fine... Not sure yet what is going on...

**Comment by croxis** [comment] 2021-07-25 03:39
Would it help if I shared my git repository?

**Comment by BastiaanOlij** [comment] 2021-07-25 08:15
that may help as I just tried one of my projects on the Quest that uses the viewport and it works.

**Comment by croxis** [comment] 2021-07-25 20:07
https://gitlab.com/croxis/ITF

Its hard coded for openvr at the moment. Pull one of the triggers (forget if i set it to left or right) during the excessive title sequence it should put you in the bridge with the non working display.

The node in question is in the file shared/ships/earth_alliance/babylon_5/babylon_5_net.tscn and the node is Viewport2Din3D

**Comment by BastiaanOlij** [comment] 2021-08-01 12:08
hey @croxis,

Sorry for the late response mate, busy times. Finally had time to try out your project, very cool!

Okay, couple of things to explain what is going on. 

Your screen goes all white because you've turned on auto exposure. Auto exposure tries to balance the intensity, lowering it when you are in a light environment, increasing it when you're in the dark. 
Inside of your CNC things are very very dark, so the auto exposure is correcting the exposure to maximum to try and make things lighter, causing you UI to become one big glaring thing. Either the rest of the CNC needs to become much brighter, or you should try and work with fixed exposure settings and not using auto exposure.

Your UI not working is because none of the signals are setup. When you add your 2D scene to the viewport component it will instantiate this 2D scene for that viewport. That you also have a copy in your root doesn't matter, that is just another copy. I noticed that you did link up your signals there. 
You're going to have to link the signals up in the 2D scene itself and give it a script, and then pass the signal back down or implement your logic in an autoload script and call that.
I also noticed that the raycast is slightly off, I'm not sure whats causing that, I think it might have something to do with the margins on the collision shape.

I also noticed that as the cutscene flies you around the b5 spacestation the controllers completely lag behind. That is not a fault of your, it's been reported to me before but I've not seen it misbehave this badly before. I think this is a bug in Godot itself, as it processes the new controller locations it seems to be taking the parent location from before when the animation player updates the players position. Very very weird, it all seems to matter in what order positioning is done and I have a feeling the animation player is applied last resulting in this issue. I recommend hiding the controller meshes during the cutscene until we figure out a workaround.

Finally, I'm using an index with pretty much my whole living room setup as a play area. The ARVROrigin point reflects the center of my room, I'm thus sitting a meter or so away from this center. When I'm moved into the CNC I'm actually floating in space :)
You might want to add an `ARVRServer.center_on_hmd` call before you place the player inside of the CNC so they start in the position you want them to be. Obviously I can still walk "outside" but that would now be my own fault :)

**Comment by croxis** [comment] 2021-08-04 21:05
Thank you for taking the time to look at it and helping me with all my learning mistakes. If I was smart I would of started with a nice simple single player 2d project.

The only issue I have left is the raycast with Viewport_2D_in_3D. I seem to be able to "mouse over" the join button, but the virtual cursor seems offset in the opposite direction of the drift of the dot. Could this be related to the bug where the controllers lag behind? The ARVR player is rotating with the station.

**Comment by BastiaanOlij** [comment] 2021-08-06 08:46
Yeah I noticed that, I don't think it's lag, I think it has to do with the size of the collision object I'm using to detect where the raycast is hitting the screen, I need to do some more experimenting with that.

**Comment by paacardoso** [comment] 2022-03-01 22:04
Hi,
I just noticed that if you have a Sprite3D node (that uses a Viewport Texture) before the Viewport node, I also get the same error.
However, if i put the Sprite3D node after the Viewport node, the error no longer appear.
So, to be more clear:

This works !!
![2022-03-01-21:58:07-screenshot](https://user-images.githubusercontent.com/11839951/156256161-99ef8796-0da0-46c0-9898-db6e07efe01b.png)

This does **not** work !!
![2022-03-01-21:58:18-screenshot](https://user-images.githubusercontent.com/11839951/156256189-0e540bb2-40b6-4e5d-a98a-0fc90c09e091.png)

**Comment by BastiaanOlij** [comment] 2023-08-29 01:13
We cleaned up `Viewport2Din3D` a while ago.
Closing this.
If there are any remaining issues, please open a new issue with a fresh reproducible case.

(note, we do except any left over issues in Godot 3 as they are unlikely to be fixed upstream and these are warnings, not errors).

**Closed by BastiaanOlij** 2023-08-29 01:13 UTC
